name: Deploy to main server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SERVICE_NAME: monolithic
      PROJECT_ID: deskito
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: checkout
      uses: actions/checkout@v4
      # with:
      #   ssh-key: ${{ secrets.SSH_KEY }}
      #   submodules: recursive

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS_KEY }}'
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
        
    - name: Configure Docker Client
      run:  |-
        gcloud auth configure-docker --quiet
    
    - name: Build and push container image
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./ci/Dockerfile.prod
        push: true
        tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
        
    - name: Deploy to Cloud Run
      run: gcloud run deploy ${{ env.SERVICE_NAME }}
        --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
        --platform managed
        --region asia-northeast3
        --port 80
        --cpu=1
        --memory=1024Mi
        --cpu-boost
        --min-instances=0
        --max-instances=10
        --execution-environment=gen1
        --allow-unauthenticated
        --quiet